spring:
  # H2 데이터베이스 사용 설정
  datasource:
    # url: jdbc:h2:mem:testdb     # 인메모리 DB (서버 끄면 데이터 사라짐)
    url: jdbc:h2:file:./qrp-db  # 파일 기반 DB (서버를 다시 켜도 데이터 유지)
    driver-class-name: org.h2.Driver
    username: sa
    password:

  # JPA 및 Hibernate 설정
  jpa:
    hibernate:
      ddl-auto: create-drop # 서버 시작 시 스키마 생성, 종료 시 삭제
    properties:
      hibernate:
        # H2 데이터베이스 방언(Dialect) 설정
        dialect: org.hibernate.dialect.H2Dialect
        # 실행되는 SQL 쿼리를 로그로 확인
        show_sql: true
        format_sql: true

  # H2 콘솔 설정
  h2:
    console:
      enabled: true
      path: /h2-console